In [1]:
import pandas as pd

months_fi = {1:'tammi', 2:'helmi', 3:'maalis', 4:'huhti', 5:'touko', 6:'kesä', 7:'heinä', 8:'elo', 9:'syys', 10:'loka', 11:'marras', 12:'joulu'}

day_cols = ['DAY_HEMS_VFR', 'DAY_BELOW_MIN', 'DAY_VFR500',
            'DAY_HEMS_IFR_CLOUD_BREAK', 'DAY_HEMS_IFR_APCH',
            'DAY_IFR_ICING', 'DAY_IFR_NO_ALTERNATE',
            'DAY_IFR_NO_CLOUD_BREAK']
night_cols = ['NIGHT_HEMS_VFR', 'NIGHT_BELOW_MIN',
              'NIGHT_VFR_HEMS_FEW_CLOUD', 'NIGHT_HEMS_IFR_CLOUD_BREAK',
              'NIGHT_HEMS_IFR_APCH', 'NIGHT_IFR_ICING',
              'NIGHT_IFR_NO_ALTERNATE', 'NIGHT_IFR_NO_CLOUD_BREAK']

In [2]:
scn_vfr0_notaf = pd.read_excel('output/HEMS_SCN_VFR0_notaf.xlsx')
scn_vfr0 = pd.read_excel('output/HEMS_SCN_VFR0.xlsx')
scn_ifr0 = pd.read_excel('output/HEMS_SCN_IFR0.xlsx')
scn_ifr3 = pd.read_excel('output/HEMS_SCN_IFR3.xlsx')
scn_ifr31 = pd.read_excel('output/HEMS_SCN_IFR3.1.xlsx')
scn_ifr32 = pd.read_excel('output/HEMS_SCN_IFR3.2.xlsx')

In [3]:
vfr_on_scene = pd.read_excel('output/HEMS_VFR_on_scene.xlsx')

In [4]:
vfr_on_scene.rename(columns={'s_DAY_HEMS_VFR': 'DAY_HEMS_VFR',
       's_DAY_BELOW_VFR':'DAY_BELOW_VFR', 's_DAY_VFR500':'DAY_VFR500', 's_NIGHT_HEMS_VFR':'NIGHT_HEMS_VFR',
       's_NIGHT_BELOW_VFR':'NIGHT_BELOW_VFR', 's_NIGHT_VFR_HEMS_FEW_CLOUD':'NIGHT_VFR_HEMS_FEW_CLOUD'}, inplace=True)
vfr_on_scene.rename(columns={'n_VFR_OK': 'n_HEMS_OK', 'VFR_OK':'HEMS_OK'}, inplace=True)
scn_vfr0_notaf.rename(columns={'n_VFR_OK': 'n_HEMS_OK', 'VFR_OK':'HEMS_OK'}, inplace=True)
scn_vfr0.rename(columns={'n_VFR_OK': 'n_HEMS_OK', 'VFR_OK':'HEMS_OK'}, inplace=True)

In [5]:
scn_ifr0['NIGHT_VFR_HEMS_FEW_CLOUD'] = 0
scn_ifr3['NIGHT_VFR_HEMS_FEW_CLOUD'] = 0
scn_ifr31['NIGHT_VFR_HEMS_FEW_CLOUD'] = 0
scn_ifr32['NIGHT_VFR_HEMS_FEW_CLOUD'] = 0

scn_ifr0.rename(columns={'DAY_BELOW_IFR': 'DAY_BELOW_MIN'}, inplace=True)
scn_ifr0.rename(columns={'NIGHT_BELOW_IFR': 'NIGHT_BELOW_MIN'}, inplace=True)
scn_ifr3.rename(columns={'DAY_BELOW_IFR': 'DAY_BELOW_MIN'}, inplace=True)
scn_ifr3.rename(columns={'NIGHT_BELOW_IFR': 'NIGHT_BELOW_MIN'}, inplace=True)
scn_ifr31.rename(columns={'DAY_BELOW_IFR': 'DAY_BELOW_MIN'}, inplace=True)
scn_ifr31.rename(columns={'NIGHT_BELOW_IFR': 'NIGHT_BELOW_MIN'}, inplace=True)
scn_ifr32.rename(columns={'DAY_BELOW_IFR': 'DAY_BELOW_MIN'}, inplace=True)
scn_ifr32.rename(columns={'NIGHT_BELOW_IFR': 'NIGHT_BELOW_MIN'}, inplace=True)

scn_vfr0_notaf.rename(columns={'DAY_BELOW_VFR': 'DAY_BELOW_MIN'}, inplace=True)
scn_vfr0_notaf.rename(columns={'NIGHT_BELOW_VFR': 'NIGHT_BELOW_MIN'}, inplace=True)
scn_vfr0.rename(columns={'DAY_BELOW_VFR': 'DAY_BELOW_MIN'}, inplace=True)
scn_vfr0.rename(columns={'NIGHT_BELOW_VFR': 'NIGHT_BELOW_MIN'}, inplace=True)
vfr_on_scene.rename(columns={'DAY_BELOW_VFR': 'DAY_BELOW_MIN'}, inplace=True)
vfr_on_scene.rename(columns={'NIGHT_BELOW_VFR': 'NIGHT_BELOW_MIN'}, inplace=True)

scn_ifr0.rename(columns={'DAY_HEMS_IFR': 'DAY_HEMS_IFR_CLOUD_BREAK'}, inplace=True)
scn_ifr0.rename(columns={'NIGHT_HEMS_IFR': 'NIGHT_HEMS_IFR_CLOUD_BREAK'}, inplace=True)
scn_ifr0['DAY_HEMS_IFR_APCH'] = 0
scn_ifr0['NIGHT_HEMS_IFR_APCH'] = 0

scn_vfr0_notaf['DAY_HEMS_IFR_CLOUD_BREAK'] = 0
scn_vfr0_notaf['NIGHT_HEMS_IFR_CLOUD_BREAK'] = 0
scn_vfr0['DAY_HEMS_IFR_CLOUD_BREAK'] = 0
scn_vfr0['NIGHT_HEMS_IFR_CLOUD_BREAK'] = 0
vfr_on_scene['DAY_HEMS_IFR_CLOUD_BREAK'] = 0
vfr_on_scene['NIGHT_HEMS_IFR_CLOUD_BREAK'] = 0

scn_vfr0_notaf['DAY_HEMS_IFR_APCH'] = 0
scn_vfr0_notaf['NIGHT_HEMS_IFR_APCH'] = 0
scn_vfr0['DAY_HEMS_IFR_APCH'] = 0
scn_vfr0['NIGHT_HEMS_IFR_APCH'] = 0
vfr_on_scene['DAY_HEMS_IFR_APCH'] = 0
vfr_on_scene['NIGHT_HEMS_IFR_APCH'] = 0

scn_vfr0_notaf['DAY_IFR_ICING'] = 0
scn_vfr0_notaf['NIGHT_IFR_ICING'] = 0
scn_vfr0['DAY_IFR_ICING'] = 0
scn_vfr0['NIGHT_IFR_ICING'] = 0
vfr_on_scene['DAY_IFR_ICING'] = 0
vfr_on_scene['NIGHT_IFR_ICING'] = 0

scn_vfr0_notaf['DAY_IFR_NO_ALTERNATE'] = 0
scn_vfr0_notaf['NIGHT_IFR_NO_ALTERNATE'] = 0
scn_vfr0['DAY_IFR_NO_ALTERNATE'] = 0
scn_vfr0['NIGHT_IFR_NO_ALTERNATE'] = 0
vfr_on_scene['DAY_IFR_NO_ALTERNATE'] = 0
vfr_on_scene['NIGHT_IFR_NO_ALTERNATE'] = 0

scn_vfr0_notaf['DAY_IFR_NO_CLOUD_BREAK'] = 0
scn_vfr0_notaf['NIGHT_IFR_NO_CLOUD_BREAK'] = 0
scn_vfr0['DAY_IFR_NO_CLOUD_BREAK'] = 0
scn_vfr0['NIGHT_IFR_NO_CLOUD_BREAK'] = 0
vfr_on_scene['DAY_IFR_NO_CLOUD_BREAK'] = 0
vfr_on_scene['NIGHT_IFR_NO_CLOUD_BREAK'] = 0

In [6]:
scn_vfr0_notaf.insert(loc=0, column='scenario', value='VFR0_noTAF_05MAY22')
scn_vfr0.insert(loc=0, column='scenario', value='VFR0_05MAY22')
vfr_on_scene.insert(loc=0, column='scenario', value='VFR0_sector_04MAY22')
scn_ifr0.insert(loc=0, column='scenario', value='IFR0_09MAY22')
scn_ifr3.insert(loc=0, column='scenario', value='IFR3_10MAY22')
scn_ifr31.insert(loc=0, column='scenario', value='IFR3.1_10MAY22')
scn_ifr32.insert(loc=0, column='scenario', value='IFR3.2_10MAY22')

In [7]:
scns = [scn_vfr0_notaf, scn_vfr0, scn_ifr0, scn_ifr3, scn_ifr31, scn_ifr32, vfr_on_scene]

In [8]:
wide = pd.concat(scns)
wide.insert(loc=1, column='base', value=wide['sector'].str.slice(0,4))
wide.insert(loc=4, column='month_txt', value=wide['month'].map(months_fi))
wide.insert(loc=7, column='n_NIGHT', value=wide[night_cols].sum(axis=1))
wide.insert(loc=7, column='n_DAY', value=wide[day_cols].sum(axis=1))
wide = wide[[c for c in wide if c not in ['n_HEMS_OK', 'HEMS_OK']] 
       + ['n_HEMS_OK', 'HEMS_OK']]

In [9]:
scn_vfr0_notaf.drop(columns=['n_HEMS_OK', 'HEMS_OK'], inplace=True, errors='ignore')
scn_vfr0.drop(columns=['n_HEMS_OK', 'HEMS_OK'], inplace=True, errors='ignore')
vfr_on_scene.drop(columns=['n_HEMS_OK', 'HEMS_OK'], inplace=True, errors='ignore')

scn_ifr0.drop(columns=['n_HEMS_OK', 'HEMS_OK'], inplace=True, errors='ignore')
scn_ifr3.drop(columns=['n_HEMS_OK', 'HEMS_OK'], inplace=True, errors='ignore')
scn_ifr31.drop(columns=['n_HEMS_OK', 'HEMS_OK'], inplace=True, errors='ignore')
scn_ifr32.drop(columns=['n_HEMS_OK', 'HEMS_OK'], inplace=True, errors='ignore')

In [10]:
scn_vfr0_notaf.drop(columns=['n'], inplace=True, errors='ignore')
scn_vfr0.drop(columns=['n'], inplace=True, errors='ignore')
scn_ifr0.drop(columns=['n'], inplace=True, errors='ignore')
scn_ifr3.drop(columns=['n'], inplace=True, errors='ignore')
scn_ifr31.drop(columns=['n'], inplace=True, errors='ignore')
scn_ifr32.drop(columns=['n'], inplace=True, errors='ignore')
vfr_on_scene.drop(columns=['n'], inplace=True, errors='ignore')

In [11]:
print(len(scn_vfr0_notaf.columns))
print(len(scn_vfr0.columns))
print(len(scn_ifr0.columns))
print(len(scn_ifr3.columns))
print(len(scn_ifr31.columns))
print(len(scn_ifr32.columns))
print(len(vfr_on_scene.columns))

20
20
20
20
20
20
20

In [12]:
melted = []
for scn in scns:
       df = pd.melt(scn, id_vars=['scenario', 'sector', 'month', 'hour'], value_vars=['DAY_HEMS_VFR',
              'DAY_BELOW_MIN', 'DAY_VFR500', 'NIGHT_HEMS_VFR', 'NIGHT_BELOW_MIN',
              'NIGHT_VFR_HEMS_FEW_CLOUD', 'DAY_HEMS_IFR_CLOUD_BREAK',
              'NIGHT_HEMS_IFR_CLOUD_BREAK', 'DAY_HEMS_IFR_APCH',
              'NIGHT_HEMS_IFR_APCH', 'DAY_IFR_ICING', 'NIGHT_IFR_ICING',
              'DAY_IFR_NO_ALTERNATE', 'NIGHT_IFR_NO_ALTERNATE',
              'DAY_IFR_NO_CLOUD_BREAK', 'NIGHT_IFR_NO_CLOUD_BREAK'], var_name='class', value_name='n')
       melted.append(df)

long = pd.concat(melted)

In [13]:
long.insert(loc=1, column='base', value=long['sector'].str.slice(0,4))
long.insert(loc=4, column='month_txt', value=long['month'].map(months_fi))
long.insert(loc=6, column='night', value=long['class'].str.startswith('NIGHT'))

In [14]:
long.sort_values(by=['scenario', 'sector', 'month', 'hour', 'class'], inplace=True)

In [15]:
long

,scenario,base,sector,month,month_txt,hour,night,class,n
25056,IFR0_09MAY22,FH10,FH10.1,1,tammi,0,False,DAY_BELOW_MIN,0
200448,IFR0_09MAY22,FH10,FH10.1,1,tammi,0,False,DAY_HEMS_IFR_APCH,0
150336,IFR0_09MAY22,FH10,FH10.1,1,tammi,0,False,DAY_HEMS_IFR_CLOUD_BREAK,0
0,IFR0_09MAY22,FH10,FH10.1,1,tammi,0,False,DAY_HEMS_VFR,0
250560,IFR0_09MAY22,FH10,FH10.1,1,tammi,0,False,DAY_IFR_ICING,0
...,...,...,...,...,...,...,...,...,...
85247,VFR0_sector_04MAY22,FH80,FH80.base,12,joulu,23,True,NIGHT_HEMS_VFR,207
285695,VFR0_sector_04MAY22,FH80,FH80.base,12,joulu,23,True,NIGHT_IFR_ICING,0
335807,VFR0_sector_04MAY22,FH80,FH80.base,12,joulu,23,True,NIGHT_IFR_NO_ALTERNATE,0
385919,VFR0_sector_04MAY22,FH80,FH80.base,12,joulu,23,True,NIGHT_IFR_NO_CLOUD_BREAK,0
135359,VFR0_sector_04MAY22,FH80,FH80.base,12,joulu,23,True,NIGHT_VFR_HEMS_FEW_CLOUD,36

In [16]:
wide

,scenario,base,sector,month,month_txt,hour,n,n_DAY,n_NIGHT,DAY_HEMS_VFR,...,DAY_HEMS_IFR_APCH,NIGHT_HEMS_IFR_APCH,DAY_IFR_ICING,NIGHT_IFR_ICING,DAY_IFR_NO_ALTERNATE,NIGHT_IFR_NO_ALTERNATE,DAY_IFR_NO_CLOUD_BREAK,NIGHT_IFR_NO_CLOUD_BREAK,n_HEMS_OK,HEMS_OK
0,VFR0_noTAF_05MAY22,FH10,FH10.1,1,tammi,0,366,0,366,0,...,0,0,0,0,0,0,0,0,140,0.382514
1,VFR0_noTAF_05MAY22,FH10,FH10.1,1,tammi,1,369,0,369,0,...,0,0,0,0,0,0,0,0,132,0.357724
2,VFR0_noTAF_05MAY22,FH10,FH10.1,1,tammi,2,367,0,367,0,...,0,0,0,0,0,0,0,0,128,0.348774
3,VFR0_noTAF_05MAY22,FH10,FH10.1,1,tammi,3,366,0,366,0,...,0,0,0,0,0,0,0,0,117,0.319672
4,VFR0_noTAF_05MAY22,FH10,FH10.1,1,tammi,4,370,0,370,0,...,0,0,0,0,0,0,0,0,133,0.359459
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25051,VFR0_sector_04MAY22,FH60,FH60_2.3,12,joulu,19,599,0,599,0,...,0,0,0,0,0,0,0,0,167,0.278798
25052,VFR0_sector_04MAY22,FH60,FH60_2.3,12,joulu,20,582,0,582,0,...,0,0,0,0,0,0,0,0,163,0.280069
25053,VFR0_sector_04MAY22,FH60,FH60_2.3,12,joulu,21,587,0,587,0,...,0,0,0,0,0,0,0,0,173,0.294719
25054,VFR0_sector_04MAY22,FH60,FH60_2.3,12,joulu,22,580,0,580,0,...,0,0,0,0,0,0,0,0,175,0.301724
25055,VFR0_sector_04MAY22,FH60,FH60_2.3,12,joulu,23,581,0,581,0,...,0,0,0,0,0,0,0,0,169,0.290878

In [17]:
with pd.ExcelWriter("output/HEMS_SCN_combined.xlsx") as writer:
    long[long['n'] != 0].to_excel(writer, 'long', index=False, freeze_panes=(1, 0))
    wide.to_excel(writer, 'wide', index=False, freeze_panes=(1, 0))